### ISSUE TITLE
Can we get more specifics on number of calls we can make in a given timeframe?

### ISSUE THREAD

**Issue by dbragdon1** [hnrss/hnrss#50]
Sorry if the title doesn't make much sense. I have built a pipeline for automatically scraping new hackernews comments and I'm wondering how often I can call the server to check for new comments. I'm currently checking for new comments every 10 seconds, in which I make a new call using python's ```feedparser``` to check for any new comments not included in the last call. It seems like the parser only returns a maximum of 20 new comments every ~5/6 minutes. I'd like to get comments more frequently, and I'm wondering if I am reaching the limit on the number of calls to the server. 

Otherwise, this is a great project and it has been very useful for my work. Thank you for all you've been doing!

**Comment by edavis** [comment]
Howdy @dbragdon1!

All endpoints are cached for 5 minutes and that appears to be what you're running into.

For something like this you're better off using the Algolia API (https://hn.algolia.com/api) or the official API (https://github.com/HackerNews/API) directly.

hnrss uses the Algolia API under the hood, so that would probably be the easiest to move to. For /newcomments, the underlying Algolia API call is `https://hn.algolia.com/api/v1/search_by_date?tags=comment`.

Hope this helps!
