### ISSUE TITLE
Count not working for alternative feeds

### ISSUE THREAD

**Issue by ghost** [hnrss/hnrss#51]
Hi!
First of all, thanks for hnrss, it is awesome! :)
I just discovered that there is the `count` parameter, but it seems like it doesn't affect the alternative feeds at all.
Here is an example:
```
https://hnrss.org/best?count=5
```
It still gives back 30 feeds (the default value)

**Comment by edavis** [comment]
Hi @bobicino — Thanks! Yeah, unfortunately, this is the case.

It's due to the fact that the alternative feeds (https://github.com/hnrss/hnrss/blob/master/main.go#L43-L49) first scrape its respective HTML on Hacker News to collect IDs, then queries Algolia with those IDs to build the feeds.

That initial ID collection is what determines how many results to return. I suppose I could rig something up so that if `count` is smaller than the number of IDs collected, `count` results are returned. But if `count` is greater than the number of IDs collected, it would still be capped at the number of IDs.

Refs: hnrss/hnrss.github.io#4
