### ISSUE TITLE
Second Chance Pool stories are getting missed

### ISSUE THREAD

**Issue by rajnathani** [hnrss/hnrss#70]
Most HN stories in the second chance pool do not show up in HNRSS. (https://news.ycombinator.com/pool)

One approach is to increase the time window to about one-two weeks to check for points threshold surpass.

**Comment by rajnathani** [comment]
Hello,
The category I am referring to is in the general feed, for example 40+ points one which I happen to use:
https://hnrss.org/newest?points=40

**Comment by edavis** [comment]
Hi @rajnathani — Thanks for the clarification.

While I see what you're getting at here, at a technical level everything is working as expected. Second chance pool stories do appear in `/newest` and if they have enough points to clear the threshold they appear in `/newest?points=X`, too.

I would be against building special handling into `/newest` for this. Especially because you can subscribe directly to `/pool` if you want to make sure you don't miss any second chance pool stories.

Hope my reasoning makes sense. Have a good one.
